In [1]:
import numpy as np

Trabajaremos con el archivo posicion_velocidad_coment.dat que se muestra aquí:


```#posicion velocidad
0.0  30
0.8  50
1.5  43.2
2.0  20.0
2.6  42.1```

In [2]:
str_archivo = 'data/Clases/posicion_velocidad_coment.dat'

# Función loadtxt

Usamos la función loadtxt de numpy que nos permite procesar archivos con datos númericos

In [3]:
np.loadtxt?

Existen las opciones de definir el tipo de información a procesar como float, string, double etc, el delimitador de los valores y el saltar los primeras n lineas con skiprows.

In [5]:
np.loadtxt(str_archivo)

array([[  0. ,  30. ],
       [  0.8,  50. ],
       [  1.5,  43.2],
       [  2. ,  20. ],
       [  2.6,  42.1]])

In [9]:
data = np.loadtxt(str_archivo)

In [10]:
data[:,0]

array([ 0. ,  0.8,  1.5,  2. ,  2.6])

In [11]:
data[:,1]

array([ 30. ,  50. ,  43.2,  20. ,  42.1])

In [12]:
x = data[:,0]

In [13]:
v = data[:,1]

In [14]:
x, v

(array([ 0. ,  0.8,  1.5,  2. ,  2.6]),
 array([ 30. ,  50. ,  43.2,  20. ,  42.1]))

Ahora importamos directamente en las dos variables con opción "unpack"

In [15]:
x,v  = np.loadtxt(str_archivo,unpack=True)

In [16]:
x

array([ 0. ,  0.8,  1.5,  2. ,  2.6])

# Función genfromtxt

Usamos la alternativa de genfromtxt para trabajar con archivos incompletos de datos y para tener mayor flexibilidad en el procesamiento.


In [6]:
np.genfromtxt?

El archivo posicion_velocidad_missing.dat le falta un valor en la velocidad:

```@ Archivo obtenido el 30 diciembre 2016
0.0  30
0.8  50
1.5  43.2
2.0  Bla 
2.6  42.1```

In [18]:
str_archivo = 'data/Clases/posicion_velocidad_missing.dat'
data = np.genfromtxt(str_archivo,comments='@')

In [19]:
data

array([[  0. ,  30. ],
       [  0.8,  50. ],
       [  1.5,  43.2],
       [  2. ,   nan],
       [  2.6,  42.1]])

Como cambiamos el valor del item ausente?

In [20]:
data = np.genfromtxt(str_archivo,comments='@',filling_values='0.0')

In [21]:
data

array([[  0. ,  30. ],
       [  0.8,  50. ],
       [  1.5,  43.2],
       [  2. ,   0. ],
       [  2.6,  42.1]])

Cómo podemos procesar la nombre de la variable de los valores que se esta leyendo. 

Como ejemplo se usará el archivo posicion_velocidad_names.dat:

```@ Archivo obtenido el 30 diciembre 2016
x    v
0.0  30
0.8  50
1.5  43.2
2.0  Bla 
2.6  42.1```

In [22]:
str_archivo = 'data/Clases/posicion_velocidad_names.dat'
data1 = np.genfromtxt(str_archivo,skip_header=1,names=True,filling_values='0.0')

In [23]:
data1

array([(0.0, 30.0), (0.8, 50.0), (1.5, 43.2), (2.0, 0.0), (2.6, 42.1)], 
      dtype=[('x', '<f8'), ('v', '<f8')])

In [24]:
type(data1)

numpy.ndarray

In [25]:
data1['v']

array([ 30. ,  50. ,  43.2,   0. ,  42.1])

In [26]:
data1['x']

array([ 0. ,  0.8,  1.5,  2. ,  2.6])

In [27]:
np.genfromtxt?

## Guardar array de datos en archivo

In [7]:
x = np.array([[0, 1, 2 ],[2, 3, 4]])

In [8]:
f = open('data/Clases/array.bin','w')
x.tofile(f)

In [9]:
f.close()

In [14]:
y = np.fromfile('data/Clases/array.bin', dtype=int)

In [19]:
np.fromfile?

### se guarda en forma binaria sin información alguna sobre el tipo de variable. Aparte la forma de guardar los datos depende del sistema operativo que se usa. Por eso se recomienda usar la opción save y load de numpy.

In [23]:
x

array([[0, 1, 2],
       [2, 3, 4]])

In [58]:
np.save?

In [24]:
f = open('data/Clases/array.bin','w')
np.save(f,x)

In [25]:
f.close()

In [26]:
f = open('data/Clases/array.bin','r')

In [27]:
y = np.load(f)

In [28]:
y

array([[0, 1, 2],
       [2, 3, 4]])

In [64]:
f.close()

### También se puede guardar en forma de texto sacrificando precisión y espacio de disco

In [21]:
np.savetxt?

In [29]:
np.savetxt('data/Clases/array.dat',x,fmt="%d")

In [20]:
np.loadtxt?

In [30]:
y = np.loadtxt('data/Clases/array.dat')

In [31]:
type(y[0][1])

numpy.float64

In [32]:
type(x[0][1])

numpy.int32

In [85]:
y = np.loadtxt('data/Clases/array.dat',dtype=int)

In [33]:
type(y[0][1])

numpy.float64

In [22]:
y

array([0, 1, 2, 2, 3, 4])