1.En esta práctica usted ejercitará y explorará algunas características del poderoso módulo Numpy.
Para ello, cargue el módulo usando:

In [2]:
import numpy as np

2.En Numpy existe una función llamada arange que es muy similar a la ya conocida función
range. La diferencia es que range genera una lista mientras que arange genera un arreglo
de Numpy. Para comprobar esto, ejecute:

In [9]:
x=range(10)
y=np.arange(10)
print(x,type(x))
print(y,type(y))

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], <type 'list'>)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), <type 'numpy.ndarray'>)


En otras palabras, arange(10) es equivalente a array(range(10)).

3.Usando arreglos de Numpy es posible realizar muchos cálculos en forma rápida y eficiente,
sin necesidad de recurrir a ciclos (for o while). Por ejemplo, puede calcular la misma suma
calculada en el punto 2 de la guía 03 usando

In [17]:
x = np.arange(101)
print(x)
suma = sum(1. / 2. ** x)
suma2 = sum(2. ** - x)
print(suma, suma2)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
(2.0, 2.0)


4.Adapte la idea del cálculo en el punto anterior para implementar un cálculo alternativo para el
factorial de un número n (entero positivo), pero esta vez usando un arreglo de Numpy y la función
prod() que calcula el producto de cada componente de un arreglo de Numpy (similarmente a
como sum() calcula la suma).

In [51]:
def factorial(n):
    if n > 0:
        x = np.linspace(1, n, n)
        expr = np.prod(x)
        return expr
factorial(20)

2.43290200817664e+18

5.Verifique que, a diferencia de su pariente range(), la función arange() también funciona con
pasos decimales, por ejemplo

In [55]:
print(arange(1,10,0.3))

[ 1.   1.3  1.6  1.9  2.2  2.5  2.8  3.1  3.4  3.7  4.   4.3  4.6  4.9  5.2
  5.5  5.8  6.1  6.4  6.7  7.   7.3  7.6  7.9  8.2  8.5  8.8  9.1  9.4  9.7]


6.Otra función muy útil para crear arreglos de valores en un intervalo es linspace(), que tiene
el formato linspace(desde,hasta,numero de elementos). Por ejemplo, ejecute los siguientes
comandos:

In [5]:
x=np.linspace(1,10,20)
y=np.linspace(-np.pi,np.pi,100)
print(x,np.size(x))
print(y,np.size(y))

(array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ]), 20)
(array([-3.14159265, -3.07812614, -3.01465962, -2.9511931 , -2.88772658,
       -2.82426006, -2.76079354, -2.69732703, -2.63386051, -2.57039399,
       -2.50692747, -2.44346095, -2.37999443, -2.31652792, -2.2530614 ,
       -2.18959488, -2.12612836, -2.06266184, -1.99919533, -1.93572881,
       -1.87226229, -1.80879577, -1.74532925, -1.68186273, -1.61839622,
       -1.5549297 , -1.49146318, -1.42799666, -1.36453014, -1.30106362,
       -1.23759711, -1.17413059, -1.11066407, -1.04719755, -0.98373103,
       -0.92026451, -0.856798  , -0.79333148, -0.72986496, -0.66639844,
       -0.60293192, -0.53946541, -0.47599889, -0.41253237, -0.34906585,
       -0.28559933, -0.222132

7.Otra propiedad importante de los arreglos es que sus elementos pueden usarse para iterar en
un ciclo for. Para ver esto, ejecute:

In [9]:
x = np.arange(11)
print(x, len(x))

y = x ** 2
print(y, len(y))

for i in x:
    print ("la componente "+str(i)+" de y es igual a "+str(y[i]))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 11)
(array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100]), 11)
la componente 0 de y es igual a 0
la componente 1 de y es igual a 1
la componente 2 de y es igual a 4
la componente 3 de y es igual a 9
la componente 4 de y es igual a 16
la componente 5 de y es igual a 25
la componente 6 de y es igual a 36
la componente 7 de y es igual a 49
la componente 8 de y es igual a 64
la componente 9 de y es igual a 81
la componente 10 de y es igual a 100


8.Considere el archivo de datos datos.txt. Numpy contiene la función genfromtxt, que lee datos
desde un archivo y los asigna a un arreglo, de la dimensión apropiada. Ejecute (en la misma
carpeta donde está el archivo datos.txt) los siguientes comandos:

In [2]:
import numpy as np

d = np.genfromtxt("datos.txt")
x = d[:,0]
y = d[:,1]

print(d)

[[ 0.1    0.738]
 [ 0.25   0.826]
 [ 0.41   0.981]
 [ 0.56   0.974]
 [ 0.71   0.915]
 [ 0.86   0.897]
 [ 1.02   0.739]
 [ 1.17   0.785]
 [ 1.32   0.635]
 [ 1.47   0.52 ]
 [ 1.63   0.49 ]
 [ 1.78   0.428]
 [ 1.93   0.497]
 [ 2.08   0.355]
 [ 2.24   0.359]
 [ 2.39   0.328]
 [ 2.54   0.44 ]
 [ 2.69   0.441]
 [ 2.85   0.433]
 [ 3.     0.419]]


La primera línea carga los datos al arreglo de Las últimas dos líneas asignan la primera columna
de datos al arreglo x y la segunda columna a y. Usando las funciones shape y size de Numpy,
verifique la forma y tamaño de los arreglos d, x e y. Asegúrese de entender que es lo que realiza
exactamente cada comando anterior.

In [4]:
print(d.shape, x.shape, y.shape)
print(d.size, x.size, y.size)

((20L, 2L), (20L,), (20L,))
(40, 20, 20)


9.Usando lo anterior, calcule e imprima:
(a) El promedio de los valores de la primera columna. (puede usar la función sum y len para
calcular el promedio, o bien la función mean de Numpy).
(b) El promedio de los cuadrados de los valores de la segunda columna.
(c) La suma de los productos de cada elemento de la primera con la segunda columna 

In [5]:
# promedio primera columna
mean = np.mean(x)
print(mean)

# promedio de los cuadrados de segunda columna
mean2 = np.mean(y**2)
print(mean2)

# suma de los productos de cada elemento de la primera con la segunda columna 
sum_x_y = np.sum(x*y)
print(sum_x_y)

1.55
0.4199838
15.56502


10.Bonus Track (opcional): Los arreglos de Numpy también pueden contener componentes con
valores booleanos (siempre que todos los componentes lo sean). Por ejemplo,

In [40]:
x=np.arange(11)
y=(x>5)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True  True  True]


muestra que y es un arreglo cuyas componentes son verdaderas o falsas dependiendo si la
condición impuesta (x>5) se satisface en cada componente del arreglo x.

11.Bonus Track (opcional): Las funciones any() y all(), al ser aplicadas a un arreglo de
booleanos indican si alguna o todas las componentes del arreglo son verdaderas, respectivamente.
Usando el arreglo x definido en el punto anterior, entonces


In [44]:
any(x>5)

True

es verdadero porque sí existe una componente del arreglo x que es mayor que 5, en cambio

In [46]:
any(x>10)

False

es falso. Verifique en forma similar el comportamiento de all() (por ejemplo, viendo qué
entregan los comandos all(x>5) y all(x>=0)).

In [47]:
all(x>5)

False

In [48]:
all(x>=0)

True